POST http://localhost:1337/api/auth/local
Content-Type: application/json

{
    "identifier": "gerardraf@gmail.com",
    "password": "659845623741"
}
https://e6ce-190-62-3-87.ngrok-free.app/api/auth/local